//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtStationWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionRequest
    {
        public int CommID { get; set; }
        public string UserName { get; set; }
        public string CommDesc { get; set; }
        public string CommTypeID { get; set; }
        public string Status { get; set; }
        public string Approval { get; set; }
    }
}
