//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.CompilerServices;

namespace ArtStationWebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "The User Name Field is Required")]
        public string UserName { get; set; }
        //[RegularExpression(@"^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[*.!@$%^&(){}[]:;<>,.?/~_+-=|\]).{6,32}$", ErrorMessage = "The Password Must Contain " +
        //                                                                                                                     " 1.At least one digit" +
        //                                                                                                                     " 2.At least one lowercase character" +
        //                                                                                                                     " 3.At least one uppercase character" +
        //                                                                                                                     " 4.At least one special character" +
        //                                                                                                                     " 5.At least 8 characters in length, but no more than 32.")]
        [Required(ErrorMessage = "The Password Field is Required")]
        [StringLength(15,ErrorMessage = "Password must be atleast 8 characters long and at max 15 characters long",MinimumLength = 8)]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
